# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fh-ui',
                'doc_host': 'https://curtis-allan.github.io',
                'git_url': 'https://github.com/curtis-allan/fh-ui',
                'lib_path': 'fh_ui'},
  'syms': {'fh_ui.core': {'fh_ui.core.foo': ('core.html#foo', 'fh_ui/core.py')}}}
